services:
  prestashop:
    image: prestashop/prestashop:9.0.2-apache
    container_name: ps9_shop
    ports:
      - "8080:80"
    links:
      - db
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./html:/var/www/html
    environment:
      - DB_SERVER=db
      - DB_USER=prestashop
      - DB_PASSWD=prestashop_password
      - DB_NAME=prestashop
      - PS_INSTALL_AUTO=1
      - PS_DEV_MODE=1
      - PS_ERRASE_DB=1 # Warning: erases DB on restart if install runs? No, usually allows overwrite.
      - PS_DOMAIN=localhost:8080
      - PS_LANGUAGE=pl
      - PS_COUNTRY=PL
      - PS_FOLDER_ADMIN=admin-dev
      - PS_FOLDER_INSTALL=install-dev
      - ADMIN_MAIL=admin@prestashop.local
      - ADMIN_PASSWD=Admin12345678
    networks:
      - ps_network

  db:
    image: mysql:8.0
    container_name: ps9_db
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_DATABASE=prestashop
      - MYSQL_USER=prestashop
      - MYSQL_PASSWORD=prestashop_password
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - ps_network
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10

  phpmyadmin:
    image: phpmyadmin
    container_name: ps9_pma
    ports:
      - "8081:80"
    environment:
      - PMA_HOST=db
      - PMA_USER=root
      - PMA_PASSWORD=admin
    networks:
      - ps_network

volumes:
  db_data:


networks:
  ps_network:
